name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: arosenfeld/immunedb
          registry: ghcr.io
          tags: ${{ steps.meta.outputs.tags }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
