name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
      -
        name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: immunedb
          registry: ghcr.io
          addLatest: true
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
